Objective: The objective of this assignment is to gain practical experience with fundamental operations
in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on
tensors, and understanding the difference between TensorFlow constants and variables.

Q1 What are the different data structures used in Tensorflow?. Give some


TensorFlow, a popular open-source machine learning framework, provides several different data structures to efficiently handle and manipulate data for building and training machine learning models. Some of the key data structures used in TensorFlow include:
Tensors : Tensors are the fundamental building blocks in TensorFlow. They are n-dimensional arrays that represent the data in the computation graph. Tensors can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays. TensorFlow tensors can be created using functions like tf.constant(), tf.Variable(), and by performing various operations on existing tensors

In [5]:
import tensorflow as tf

# Creating tensors
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])

In [6]:
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [7]:
vector


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [8]:
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Variables: TensorFlow Variables are special tensors that can hold mutable state. They are often used to store model parameters that need to be learned during training. Variables are typically initialized with some initial values and then updated through operations.

In [9]:
# Creating a variable
initial_value = tf.random.normal(shape=(3, 3))
model_weights = tf.Variable(initial_value)

In [10]:
initial_value

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5816702 ,  0.1752523 ,  0.05947421],
       [ 0.45138225, -0.27498326,  0.9277151 ],
       [ 0.94381905, -0.89813346, -1.9400777 ]], dtype=float32)>

In [11]:
model_weights

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.5816702 ,  0.1752523 ,  0.05947421],
       [ 0.45138225, -0.27498326,  0.9277151 ],
       [ 0.94381905, -0.89813346, -1.9400777 ]], dtype=float32)>

Constants: Constants are tensors with fixed values that remain unchanged throughout the computation. They are often used for providing constant inputs or values to the computation graph.

In [12]:
# Creating a constant
pi = tf.constant(3.14159)

In [13]:
pi

<tf.Tensor: shape=(), dtype=float32, numpy=3.14159>

Placeholders (Deprecated): In older versions of TensorFlow (before TensorFlow 2.0), placeholders were used to feed data into the computation graph during training. However, placeholders have been deprecated in favor of the new tf.data API and eager execution in TensorFlow 2.0 and later.

Sparse Tensors: Sparse tensors are designed to efficiently represent tensors with a large number of zero elements. They are useful for tasks involving sparse data, such as natural language processing or certain types of neural networks.

In [14]:
indices = [[0, 1], [1, 2]]
values = [1, 2]
shape = [3, 4]
sparse_tensor = tf.SparseTensor(indices, values, shape)

In [15]:
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

Ragged Tensors: Ragged tensors are used to represent tensors with varying lengths along one or more dimensions. They are useful for sequences or nested data structures.


In [16]:
# Creating a ragged tensor
values = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])

In [17]:
values

<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>

TensorArray: TensorArray is a dynamic data structure that allows you to store tensors of different shapes and sizes. It's often used in dynamic loop constructs.

In [18]:
# Creating a TensorArray
ta = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)

In [19]:
ta


Q2 How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example


Both TensorFlow constants and variables are fundamental data structures, but they have different purposes and behaviors within a TensorFlow computation graph.
TensorFlow Constants:
Constants are tensors with fixed values that remain unchanged throughout the computation.
They are typically used to provide inputs or fixed values to the computation graph.
Constants cannot be modified or updated after they are created.
TensorFlow Variables:
Variables are tensors that hold mutable state, often used for model parameters that need to be learned during training.
They are initialized with initial values and can be updated through operations like assignments.
Variables can be used to store and update values as the model iteratively adjusts its parameters during training

In [20]:
import tensorflow as tf

# Creating a constant
a = tf.constant(5)

# Attempting to assign a new value to a constant will result in an error
try:
    a.assign(8)  # This will raise an error
except Exception as e:
    print("Error:", e)

Error: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


In [21]:
# Example of TensorFlow Variable:

import tensorflow as tf

# Creating a variable with an initial value
initial_value = tf.random.normal(shape=(3, 3))
b = tf.Variable(initial_value)

print("Initial 'b':",b)

# Assigning a new value to the variable using the assign() operation
new_value = tf.random.normal(shape=(3, 3))
b.assign(new_value)

# Now 'b' holds the new value assigned to it
print("\nUpdated 'b':", b)

Initial 'b': <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.2328939 , -0.95835745, -0.7952967 ],
       [-0.21586783, -2.5569434 ,  0.61604786],
       [ 1.0200007 , -1.2382394 ,  0.28062585]], dtype=float32)>

Updated 'b': <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 5.6255735e-02, -8.3697325e-01,  8.5272419e-01],
       [-7.2369552e-01,  2.0804033e+00,  2.4125712e-01],
       [-1.3079981e-03,  1.2011867e+00,  7.4403930e-01]], dtype=float32)>


Q3.Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

1.Matrix Addition:
Matrix addition is a basic arithmetic operation where corresponding elements of two matrices are added together to create a new matrix of the same dimensions. In TensorFlow, you can perform matrix addition using the tf.add() function or by using the + operator

In [22]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix_a, matrix_b)

# Alternatively, you can use the + operator
result_alternative = matrix_a + matrix_b

print("Matrix Addition Result:")
print(result.numpy())
print(result_alternative.numpy())

Matrix Addition Result:
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


 - Matrix Multiplication:
Matrix multiplication is a more complex operation where the dot product of rows and columns of two matrices results in a new matrix. TensorFlow provides the tf.matmul() function to perform matrix multiplication.

In [23]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix_a, matrix_b)

print("Matrix Multiplication Result:")
print(result.numpy())

Matrix Multiplication Result:
[[19 22]
 [43 50]]


- Element-wise Operations:
Element-wise operations involve applying an operation to each corresponding element of two matrices (or a matrix and a scalar). TensorFlow allows you to perform a variety of element-wise operations, such as addition, subtraction, multiplication, division, and more.

In [24]:
import tensorflow as tf

# Define a matrix and a scalar
matrix = tf.constant([[1, 2], [3, 4]])
scalar = 2

# Perform element-wise addition
result_add = matrix + scalar

# Perform element-wise multiplication
result_multiply = matrix * scalar

print("Element-wise Addition Result:")
print(result_add.numpy())

print("Element-wise Multiplication Result:")
print(result_multiply.numpy())

Element-wise Addition Result:
[[3 4]
 [5 6]]
Element-wise Multiplication Result:
[[2 4]
 [6 8]]


Task 1: Creating and Manipulating Matricek
Tc Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix Ac

In [25]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a normal distribution
A = tf.random.normal(shape=(3, 3))

# Display the value of matrix A
print("Matrix A:")
print(A)

Matrix A:
tf.Tensor(
[[-0.5447332  -0.23194817  0.7369584 ]
 [-1.0852383   0.87615263  0.77969587]
 [-1.5286026   1.4019204   1.8075902 ]], shape=(3, 3), dtype=float32)


Q3 Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix Bc

In [29]:
import tensorflow as tf

# Define the dimensions of the matrix
matrix_shape = (2, 2)

# Generate a Gaussian matrix using normal distribution
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=matrix_shape, mean=mean, stddev=stddev)

# Display the generated matrix
print("Matrix C:")
print(C.numpy())

Matrix C:
[[3.13978   1.6794708]
 [3.0863833 2.3715343]]


Q4. Perform matrix addition between matrix A and matrix B and store the results in matrix D

Matrix A has shape (3,3) while matrix B has shape(4,4) it is not possible to add these matrices as shapes are different


In [30]:
matrix1 = tf.random.normal(shape=(2,2))
matrix2 = tf.random.normal(shape=(2,2))
D = tf.add(matrix1, matrix2)
print(f'Matrix 1 :\n {matrix1.numpy()}')
print(f'\nMatrix 2 :\n {matrix2.numpy()}')
print(f'\nMatrix D :\n {D.numpy()}')

Matrix 1 :
 [[-1.5816524  -0.1571169 ]
 [-0.42580375 -0.69490945]]

Matrix 2 :
 [[-0.23910014  0.8781955 ]
 [-2.3021293   1.820642  ]]

Matrix D :
 [[-1.8207525   0.72107863]
 [-2.727933    1.1257325 ]]


Q5. Perform matrix multiplication between matrix C and matrix D and store result in matrix E

In [31]:
E = tf.matmul(C,D)

print(f'Matrix C :\n{C.numpy()}')
print(f'\nMatrix D :\n{D.numpy()}')
print(f'\nMatrix E = CxD:\n{E.numpy()}')

Matrix C :
[[3.13978   1.6794708]
 [3.0863833 2.3715343]]

Matrix D :
[[-1.8207525   0.72107863]
 [-2.727933    1.1257325 ]]

Matrix E = CxD:
[[-10.298246   4.154663]
 [-12.088926   4.895239]]


Task 2: Performing additional matrix operations

Q1. Create a matrix F with dimensions 3x3, initialized random values using Tensorflows random_uniform function.

In [32]:
# Create a matrix F
F = tf.random.uniform(shape=(3,3))
print(f'Matrix F :\n{F.numpy()}')

Matrix F :
[[0.45698702 0.5520431  0.08579326]
 [0.684667   0.88029957 0.25337815]
 [0.59423375 0.8665395  0.3201629 ]]


Q2. Calculate Transpose of Matrix F and store in Matrix G

In [33]:
# Transpose the F matrix
G = tf.transpose(F)

# Print the matrix
print(f'Matrix G :\n{G.numpy()}')

Matrix G :
[[0.45698702 0.684667   0.59423375]
 [0.5520431  0.88029957 0.8665395 ]
 [0.08579326 0.25337815 0.3201629 ]]


Q3. Calculate element wise exponential of Matrix F and store the result in matrix H

In [34]:
# Element wise exponent
H = tf.math.exp(F)

# Print matrix H
print(f'Matrix H :\n{H.numpy()}')

Matrix H :
[[1.5793084 1.7367978 1.089581 ]
 [1.9831114 2.411622  1.2883704]
 [1.8116423 2.3786652 1.3773521]]


Q4. Create a matrix I by concatenating Matrix F and matrix G horizontally

In [35]:
# Concatenate matrices F and G horizontally to create matrix I
I = tf.concat([F, G], axis=1)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix G:")
print(G.numpy())

print("\nMatrix I (Concatenated Horizontally):")
print(I.numpy())

Matrix F:
[[0.45698702 0.5520431  0.08579326]
 [0.684667   0.88029957 0.25337815]
 [0.59423375 0.8665395  0.3201629 ]]

Matrix G:
[[0.45698702 0.684667   0.59423375]
 [0.5520431  0.88029957 0.8665395 ]
 [0.08579326 0.25337815 0.3201629 ]]

Matrix I (Concatenated Horizontally):
[[0.45698702 0.5520431  0.08579326 0.45698702 0.684667   0.59423375]
 [0.684667   0.88029957 0.25337815 0.5520431  0.88029957 0.8665395 ]
 [0.59423375 0.8665395  0.3201629  0.08579326 0.25337815 0.3201629 ]]


Q5. Create a matrix J by concatenating matrix F and matrix H vertically

In [36]:
# Concatenate matrices F and H vertically to create matrix J
J = tf.concat([F, H], axis=0)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix H:")
print(H.numpy())

print("\nMatrix J (Concatenated Vertically):")
print(J.numpy())

Matrix F:
[[0.45698702 0.5520431  0.08579326]
 [0.684667   0.88029957 0.25337815]
 [0.59423375 0.8665395  0.3201629 ]]

Matrix H:
[[1.5793084 1.7367978 1.089581 ]
 [1.9831114 2.411622  1.2883704]
 [1.8116423 2.3786652 1.3773521]]

Matrix J (Concatenated Vertically):
[[0.45698702 0.5520431  0.08579326]
 [0.684667   0.88029957 0.25337815]
 [0.59423375 0.8665395  0.3201629 ]
 [1.5793084  1.7367978  1.089581  ]
 [1.9831114  2.411622   1.2883704 ]
 [1.8116423  2.3786652  1.3773521 ]]
